[workspace]
authors = ["davidlange6 <David.Lange@cern.ch>", "pfackeldey <fackeldey.peter@gmail.com>"]
channels = ["conda-forge"]
name = "courses-hsf-india-Nov2025-python"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks.start]
cmd = "jupyter lab"

[dependencies]
aiohttp = "==3.12.13"
awkward = "==2.8.10"
fsspec = "==2025.5.1"
hist = ">=2.9.0,<3"
jax = "==0.7.2"
jaxlib = "==0.7.2"
jupyterlab = "==4.4.4"
jupyterlab-deck = "==0.2.0"
jupyterlab-mathjax3 = "==4.3.0"
matplotlib = "==3.10.3"
numba = "==0.61.2"
numexpr = "==2.10.2"
numpy = "==2.2.6"
pandas = "==2.3.0"
pyarrow = "==20.0.0"
python = "==3.13.5"
dask = "==2025.5.1"
distributed = "==2025.5.1"
graphviz = ">=13.1.2,<14"
python-graphviz = ">=0.21,<0.22"
uproot = ">=5.6.8,<6"
vector = ">=1.7.0,<2"
