name: hsf-india-python
channels:
  - nvidia/label/cuda-12.9
  - conda-forge
dependencies:
  - python=3.12
  - bash_kernel
  - grpcio
  - numpy<2
  - pandas
  - scipy
  - hdf5
  - lz4
  - matplotlib
  #- numba
  - openssh
  - pandas
  - pip
  - scikit-learn
  - pip:
      - h5py
      - tensorboard
      - tensorflow[and-cuda] 
      #- tensorrt
      - torch
      - torch-geometric
      - torchvision
      #- tqdm
      - jax[cuda12]
      - nvidia-cudnn-cu12
      - xgboost



variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  
