name: hsf-india-python
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.12
  - bash_kernel
  - jax
  - tensorflow[and-cuda]
  - nvidia-cudnn-cu12
  - numpy<2
  - pandas
  - scipy
  - hdf5
  - lz4
  - matplotlib
  - numba
  - openssh
  - pandas
  - pip
  - scikit-learn
  - pip:
      - h5py


variables:
  LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
  
