name: hsf-india
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - fsspec-xrootd
  - xrootd
  - openssh
  - notebook 
  - jupyterlab
  - pip:
    - matplotlib
    # force an old version..
    - contourpy==1.0.7
#    - awkward
#    - uproot
    - numpy<2.0
#    - vector
#    - bash_kernel
